version: "3.9"

services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=1212
      - MYSQL_DATABASE=demo_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3338:3306"               # 외부 3338 → 내부 3306
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -p$$MYSQL_ROOT_PASSWORD || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: always

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    # 외부에서 redis-cli로 테스트하려면 아래 주석 해제
    # ports:
    #   - "6382:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: always

  web:
    build: ./web                 # 현재 위치의 web 폴더를 빌드 컨텍스트로 사용
    ports:
      - "9092:3000"              # 외부 9092 → 내부 3000
    environment:
      - PORT=3000                # 앱 내부 포트
      - DB_HOST=db               # mysql 서비스 이름
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=1212
      - DB_NAME=demo_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always

volumes:
  mysql_data:
  redis_data:
